### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by RedbackThomson** [vhpoet/nwjs-boilerplate#1]
In the readme it claims you can run `$ /path/to/nw .` after gulp, but there is no package.json in the build output.
Also there is no `$ gulp package` functionality. All I see is `$ gulp dist`.

**Comment by RedbackThomson** [comment]
Alright so the issue stems from a problem with your documentation. Instead of referencing the [https://github.com/vhpoet/nwjs-boilerplate](nwjs-boilerplate) repo, you actually refer to the [https://github.com/vhpoet/frontend-boilerplate/tree/nodewebkit](frontend-boilerplate%28nodewebkit%29).

**Comment by vhpoet** [comment]
@RedbackThomson `$ /path/to/nw .` opens the development version and its meant to be called in the root folder. The root folder has a package.json.

Here's the `gulp packages`
https://github.com/vhpoet/nwjs-boilerplate/blob/develop/gulpfile.js#L275

Where is the documentation referencing to https://github.com/vhpoet/frontend-boilerplate/tree/nodewebkit?

**Comment by RedbackThomson** [comment]
In your README.md, specifically under [Setup](https://github.com/vhpoet/nwjs-boilerplate/blob/develop/README.md#setup), you refer to:
`$ git clone https://github.com/vhpoet/frontend-boilerplate`
then after:
`$ ... git checkout nodewebkit`

However in that specific repository branch you redirect it to this repo.
The only fix is to change the first part to:
`$ git clone https://github.com/vhpoet/nwjs-boilerplate`
and remove the alternate checkout branch.

**Comment by vhpoet** [comment]
@RedbackThomson oh that's right. Fixed, thank you!
