### ISSUE TITLE
Syntax error in gulpfile

### ISSUE THREAD

**Issue by juhoha** [vhpoet/nwjs-boilerplate#2]
Hey,

CBA to make pull request out of this. There's a small typo in gulpfile

...
7:  webpack = require('webpack-stream'),
8: NwBuilder = require('nw-builder'),c
9:  merge = require('merge-stream');
...

**Comment by vhpoet** [comment]
@juhoha thank you! fixed in https://github.com/vhpoet/nwjs-boilerplate/commit/4c4befa9b60a6e4749dc0445b48e6aa8c1e2ac3d
