### ISSUE TITLE
Dependencies doubt

### ISSUE THREAD

**Issue by diegoaguilar** [vhpoet/nwjs-boilerplate#3]
What have you got `.htaccess` file for and how do you solve the zipping for building process?

**Comment by vhpoet** [comment]
@diegoaguilar removed the `.htaccess` in https://github.com/vhpoet/nwjs-boilerplate/commit/b132ac3f8ccb83d921ecf6f92aedf8ed590dc5dc. What do you mean by solve the zipping?
