### ISSUE TITLE
Can maximize and minimize button on the menu bar ?

### ISSUE THREAD

**Issue by zenglzh** [vhpoet/nwjs-boilerplate#4]
To maximize and minimize button set on the menu bar . I don't need a title bar.

**Comment by vhpoet** [comment]
@zenglzh I don't understand the issue. Can you elaborate?

**Comment by zenglzh** [comment]
Sorry. My app is a frameless window.Menu and the maximize button in a row.I want set maximize , minimize button on top right-hand of the menu bar.
 Such as, The menu bar on the left is menu,and maximize button on the right.

**Comment by vhpoet** [comment]
@zenglzh yes, you can remove the toolbar. Look at the `window.toolbar` in the config. https://github.com/nwjs/nw.js/wiki/manifest-format#quick-start
